USE [master]
GO

/****** Object:  Database [betcoins-dev]    Script Date: 6/27/2018 4:07:49 PM ******/
CREATE DATABASE [betcoins-dev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Betcoins', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Betcoins.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Betcoins_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Betcoins_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [betcoins-dev] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [betcoins-dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [betcoins-dev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [betcoins-dev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [betcoins-dev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [betcoins-dev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [betcoins-dev] SET ARITHABORT OFF 
GO

ALTER DATABASE [betcoins-dev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [betcoins-dev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [betcoins-dev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [betcoins-dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [betcoins-dev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [betcoins-dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [betcoins-dev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [betcoins-dev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [betcoins-dev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [betcoins-dev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [betcoins-dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [betcoins-dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [betcoins-dev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [betcoins-dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [betcoins-dev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [betcoins-dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [betcoins-dev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [betcoins-dev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [betcoins-dev] SET  MULTI_USER 
GO

ALTER DATABASE [betcoins-dev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [betcoins-dev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [betcoins-dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [betcoins-dev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [betcoins-dev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [betcoins-dev] SET QUERY_STORE = OFF
GO

USE [betcoins-dev]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [betcoins-dev] SET  READ_WRITE 
GO


